// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN_ve55lSo2nhVPAlvCgnBS9peZyp_5xo',
    appId: '1:1019224602556:web:05fa8f8f4cd3c61d1bddb9',
    messagingSenderId: '1019224602556',
    projectId: 'e-revive-78419',
    authDomain: 'e-revive-78419.firebaseapp.com',
    storageBucket: 'e-revive-78419.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUUpVC74buso0lv6mtaFnkmRkqKi2s99U',
    appId: '1:1019224602556:android:8bf710f349a5a3881bddb9',
    messagingSenderId: '1019224602556',
    projectId: 'e-revive-78419',
    storageBucket: 'e-revive-78419.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkz1Z_MqfNMGgnYOFZuUtVV2MpXeBq1yI',
    appId: '1:1019224602556:ios:4957d74c7f5715241bddb9',
    messagingSenderId: '1019224602556',
    projectId: 'e-revive-78419',
    storageBucket: 'e-revive-78419.appspot.com',
    iosBundleId: 'com.example.erevive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkz1Z_MqfNMGgnYOFZuUtVV2MpXeBq1yI',
    appId: '1:1019224602556:ios:4957d74c7f5715241bddb9',
    messagingSenderId: '1019224602556',
    projectId: 'e-revive-78419',
    storageBucket: 'e-revive-78419.appspot.com',
    iosBundleId: 'com.example.erevive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN_ve55lSo2nhVPAlvCgnBS9peZyp_5xo',
    appId: '1:1019224602556:web:08f2f5a08ba693db1bddb9',
    messagingSenderId: '1019224602556',
    projectId: 'e-revive-78419',
    authDomain: 'e-revive-78419.firebaseapp.com',
    storageBucket: 'e-revive-78419.appspot.com',
  );
}
